### ISSUE TITLE
Use the TimescaleDB Postgres extension

### ISSUE THREAD

**Issue by Hebilicious** [dcSpark/oura-postgres-sink#27]
Hello there,
I was looking at Oura when I discovered this sink that you guys have built. I was wondering if you ever heard of https://github.com/timescale/timescaledb, which is an open source PostgresQL extension designed for timeseries data. I've used it before on an IOT project and was really impressed (I am not affiliated with them).
Given the nature of blockchain data, I believe this could be a great fit (more info in their docs https://docs.timescale.com/timescaledb/latest/overview/)
I might fork this sink and implement it with Timescale myself, just wanted to open a discussion about it here first.
Thanks for building this sink !

**Comment by SebastienGllmt** [comment]
Yes, I have heard of it. Usually timeseries data fails horribly on blockchain data because of rollbacks (which are fairly frequent). For use cases where you don't care about having up-to-date data right away, you can avoid rollbacks entirely by using something like our [rollback-handler](https://github.com/dcSpark/multiverse-rs) but for use-cases like wallets (which we care particularly about), we want to have the tip even if it may get rolled back

**Comment by Hebilicious** [comment]
Looks like the https://github.com/dcSpark/multiverse-rs is private. Thanks for the quick reply, I'll close this 👍

**Comment by SebastienGllmt** [comment]
No worries. If you find a way to get timescaleDb or some other solution working well with rollbacks, let me know! But I suggest starting any investigation in timeseries storage with finding out how to handle rollbacks
